Commands:
  criar:
    class: classCriar
    options:
      controllerCriar:
        params:
          paramCriar: string
      OUTRAOPTION:
  deletar:
    class: classDeletar
    options:
      controllerDeletar:
        params:
          ParamDeletar: string
          ParamDeletar2: string
  montar: 
    class: xx
    params:
      primeiro: sgtring
