create:
  controller:
    params: {name: string, path: string}
    return: Create\controller();
  view:
    params: {name: string}
    return: Create\view();
multiply:
  params: {num1: int, num2: int}
  return: num1 * num2;
today:
  return: date("d");
positive:
  params: {num: int}
  return: num > 0 ? true : false;
