Commands:
  criar:
    class: 
    options:
      controller:
        params:
          name:
      model:
  deletar:
    class: 
    options:
      controller:
        params:
          name: 
      model:
