Commands:
  criar:
    class: classCriar
    options:
      controllerCriar:
        params:
          paramCriar: string
  deletar:
    class: classDeletar
    options:
      controllerDeletar:
        params:
          ParamDeletar: string
          ParamDeletar2: string
